"""Utility functions for the Procmon Residue Analyzer."""

from leftovers.utils.text import (
    normalize_proc_name,
    normalize_spaces,
    parse_detail,
    parse_procmon_time_to_dt,
    rot13,
    safe_int,
    split_tokens,
)
from leftovers.utils.path import (
    _replace_ci,
    category_from_type,
    cluster_from_path,
    detect_item_type,
    get_current_username,
    get_wow64_equivalents,
    map_sandbox_user_path,
    normalize_path,
    path_has_safe_prefix,
    path_is_low_value,
    path_looks_sandbox,
)
from leftovers.utils.pattern import (
    PatternDict,
    PatternList,
    compile_term_patterns,
    merge_term_patterns,
    token_hit_terms,
    token_hit_weight,
    token_hits,
)
from leftovers.utils.trust import (
    check_company_name_trusted,
    is_trusted_signed,
    read_file_version_info,
    verify_authenticode_signature,
    verify_authenticode_wintrust,
)

__all__ = [
    "PatternDict",
    "PatternList",
    "_replace_ci",
    "category_from_type",
    "check_company_name_trusted",
    "cluster_from_path",
    "compile_term_patterns",
    "detect_item_type",
    "get_current_username",
    "get_wow64_equivalents",
    "is_trusted_signed",
    "map_sandbox_user_path",
    "merge_term_patterns",
    "normalize_path",
    "normalize_proc_name",
    "normalize_spaces",
    "parse_detail",
    "parse_procmon_time_to_dt",
    "path_has_safe_prefix",
    "path_is_low_value",
    "path_looks_sandbox",
    "read_file_version_info",
    "rot13",
    "safe_int",
    "split_tokens",
    "token_hit_terms",
    "token_hit_weight",
    "token_hits",
    "verify_authenticode_signature",
    "verify_authenticode_wintrust",
]
